name: e2e
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  workflow_dispatch:
    # specify workflow inputs
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
    inputs:
      siteName:
        description: Netlify Site Name
        required: false
      deployPrimeUrl:
        description: Deployed URL
        required: true
jobs:
  show-event:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "Testing url ${{ github.event.inputs.deployPrimeUrl }}"
      - name: Dump entire event
        env:
          EVENT: ${{ toJson(github.event) }}
        run: echo "$EVENT"

      - name: Checkout ⬇️
        uses: actions/checkout@v2

      # test the deployed site using
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config: baseUrl=${{ github.event.inputs.deployPrimeUrl }}
