name: e2e
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  [push, repository_dispatch, deployment, deployment_status, workflow_dispatch]
jobs:
  show-event:
    runs-on: ubuntu-20.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
